// clears all error messages
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

// Fetch products
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED";
export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED";

export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const LOGOUT_USER = "LOGOUT_USER";


export const FETCH_ENTRIES_PENDING = "FETCH_ENTRIES_PENDING";
export const FETCH_ENTRIES_FULFILLED = "FETCH_ENTRIES_FULFILLED";
export const FETCH_ENTRIES_REJECTED = "FETCH_ENTRIES_REJECTED";


export const FETCH_APIKEYS_PENDING = "FETCH_APIKEYS_PENDING";
export const FETCH_APIKEYS_FULFILLED = "FETCH_APIKEYS_FULFILLED";
export const FETCH_APIKEYS_REJECTED = "FETCH_APIKEYS_REJECTED";


export const GENERATE_APIKEYS_PENDING = "GENERATE_APIKEYS_PENDING";
export const GENERATE_APIKEYS_FULFILLED = "GENERATE_APIKEYS_FULFILLED";
export const GENERATE_APIKEYS_REJECTED = "GENERATE_APIKEYS_REJECTED";


export const DELETE_APIKEYS_PENDING = "DELETE_APIKEYS_PENDING";
export const DELETE_APIKEYS_FULFILLED = "DELETE_APIKEYS_FULFILLED";
export const DELETE_APIKEYS_REJECTED = "DELETE_APIKEYS_REJECTED";


export const CREATE_ENTRY_PENDING = "CREATE_ENTRY_PENDING";
export const CREATE_ENTRY_FULFILLED = "CREATE_ENTRY_FULFILLED";
export const CREATE_ENTRY_REJECTED = "CREATE_ENTRY_REJECTED";

export const UPLOAD_CSV_PENDING = "UPLOAD_CSV_PENDING";
export const UPLOAD_CSV_FULFILLED = "UPLOAD_CSV_FULFILLED";
export const UPLOAD_CSV_REJECTED = "UPLOAD_CSV_REJECTED";


export const APPROVE_ENTRY_PENDING = "APPROVE_ENTRY_PENDING";
export const APPROVE_ENTRY_FULFILLED = "APPROVE_ENTRY_FULFILLED";
export const APPROVE_ENTRY_REJECTED = "APPROVE_ENTRY_REJECTED";

export const REJECT_ENTRY_PENDING = "REJECT_ENTRY_PENDING";
export const REJECT_ENTRY_FULFILLED = "REJECT_ENTRY_FULFILLED";
export const REJECT_ENTRY_REJECTED = "REJECT_ENTRY_REJECTED";



// export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING"
// export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED"
// export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED"
