// clears all error messages
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

// Fetch products
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING"
export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED"
export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED"

export const CREATE_USER_PENDING = "CREATE_USER_PENDING"
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED"
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED"


// export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING"
// export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED"
// export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED"

